name: CIEDE2000 Test in JavaScript (Arbitrary Precision)

on:
  workflow_dispatch:

env:
  n_csv_lines: 10000

jobs:
  test-ciede2000-js-arbitrary:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 📂 For each step below, a new shell will be started at the repository root
        uses: actions/checkout@v7


      - name: 📦 Set up Node, GCC and MPFR
        run: |
          command -v node > /dev/null || { sudo apt-get update --allow-unauthenticated && sudo apt-get install --allow-unauthenticated --no-install-recommends --assume-yes nodejs ; }
          command -v gcc > /dev/null || { sudo apt-get update --allow-unauthenticated && sudo apt-get install --allow-unauthenticated --no-install-recommends --assume-yes gcc ; }
          sudo apt-get update --allow-unauthenticated && sudo apt-get install --allow-unauthenticated --no-install-recommends --assume-yes libmpfr-dev libgmp-dev

      - name: 🔧 Prepare the JavaScript driver
        run: |
          printf '%s\n' '' \
          'const ciede2000 = get_ciede2000_arbitrary(50)' \
          'const canonical = 3 < process.argv.length' \
          'const fs = require("fs"), path = process.argv[2]' \
          'if (fs.existsSync(path)) {' \
          '	const lineReader = require("readline").createInterface({' \
          '		input: fs.createReadStream(process.argv[2]),' \
          '	})' \
          '	lineReader.on("line", line => {' \
          '		const de = ciede2000(...line.split(",").map(parseFloat), canonical)' \
          '		process.stdout.write(line + "," + de + "\n")' \
          '	})' \
          '}' \
          '' >> ciede2000-arbitrary-precision.js

      - name: 🌐️ Download the CIEDE2000 driver program
        run: wget --no-verbose --no-check-certificate --timeout=5 --tries=2 https://ciede2000.pages-perso.free.fr/static/github/ciede2000-arbitrary-precision-driver.c

      - name: ⚙️ Compile the CIEDE2000 driver program in C99
        run: gcc --version && gcc -std=c99 -Wall -pedantic -O2 -g ciede2000-arbitrary-precision-driver.c -o ciede2000-arbitrary -lmpfr -lgmp

      - name: 🎨 Generate ΔE2000 color difference test cases
        run: ./ciede2000-arbitrary --number $n_csv_lines --with-weights --output-file test-cases.csv

      - name: 🚀 Run test cases in JavaScript and stream to verifier
        run: |
          node ciede2000-arbitrary-precision.js test-cases.csv --canonical | ./ciede2000-arbitrary --precision 50 --output-file summary-canonical.txt &
          node ciede2000-arbitrary-precision.js test-cases.csv | ./ciede2000-arbitrary --precision 50 --output-file summary-simplified.txt &
          wait

      - name: 🏁 Conclusion
        run: |
          for compliance in simplified canonical; do
            file="summary-$compliance.txt"
            cat "$file"
            #
            if [ "${file%canonical.txt}" = "$file" ]; then
              Q1="[ ] CANONICAL [X] SIMPLIFIED"
            else
              Q1="[X] CANONICAL [ ] SIMPLIFIED"
            fi
            if grep -Fq "$Q1" "$file" && grep -Fq "Error : 0" "$file" && grep -Fq "Successes : $n_csv_lines" "$file"; then
              echo "✔️ Verification of $file successful: all $n_csv_lines color differences were correctly calculated."
            else
              echo "❌ Verification failed. See above for details."
              exit 1
            fi
          done
